set arduino_board_desc=Arduino Uno
set arduino_board_name=uno
set arduino_build_mcu=atmega328p
set arduino_build_f_cpu=16000000L
set arduino_build_core=arduino
set arduino_upload_protocol=arduino
set arduino_upload_speed=115200
set arduino_upload_maximum_size=32256
set arduino_upload_port=
set arduino_core_full_path=C:\Users\Papa\Desktop\ArduPlane\Arduino\arduino-0100-relax\hardware\arduino\cores\arduino
set arduino_project_full_path=G:\ArduRepo\ArduPlane
set avr_bin_path=C:\Users\Papa\Desktop\ArduPlane\Arduino\arduino-0100-relax\hardware\tools\avr\bin
set avr_etc_path=c:\users\papa\desktop\arduplane\arduino\arduino-0100-relax\hardware\tools\avr\etc
set arduino_compiler_include_paths= -IF:\ArduPlane\arduino-0022-relaxpatch\libraries\SPI  -IC:\Users\Papa\Desktop\ArduPlane\Arduino\arduino-0100-relax\hardware\arduino\cores\arduino -Ic:\users\papa\desktop\arduplane\arduino\arduino-0100-relax\hardware\tools\avr\avr\include\avr
set vm_do_compile=1
set vm_do_upload=0
